name = "ContactAlgorithms"
uuid = "95ce497c-b8e3-4ee7-8c85-e1ccaa9bd12a"
authors = ["Steffen Plunder, Jonathan Jahnke"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
Plots = "1.4"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
